### PR TITLE
Replace legacy Growl notifications with macOS UserNotificationCenter

### PR DESCRIPTION
**Pull request by derreisende77**
Horos minimum OS requirement is 10.11 which has OS X User Notification support. Growl hasn´t been updated for a long time and isn´t necessary.
This PR replaces Growl notifications with calls to NSUserNotificationCenter and removes the framework from the application.

Note that for some unknown reason I wasn´t able to modify the preferences Growl text. This needs to be changed if this PR gets accepted.

### CODE REVIEW

**Comment by fvpolpeta** [comment]
Hi @derreisende77 

Thanks a lot for your pull request, I will check how to change that in Preferences. You mean the label itself right?

Also, could you please confirm - according to the NSUserNotificatioCenter API - if we should have a release after the line below:

AppController.m - 3286
[[NSUserNotificationCenter defaultUserNotificationCenter] scheduleNotification:notification];
[notification release];

The way it was, I'm not sure this notification was getting released. In other words, some leak that we have the chance to fix in advance.

Thanks

Fauze

**Comment by derreisende77** [comment]
Yes I mean the label itself.

I have never seen any code calling [notification release] after scheduling it. So I THINK it will get release after it got displayed by the system. And I couldn't find any references in the docs as well.

**Comment by fvpolpeta** [comment]
Ok, thanks. I will check.

It may be hard to find references since it's no longer an active practice manage memory manually in Apps.

Cheers

**Comment by aglv** [comment]
Yes, release the notification. @derreisende77 maybe you were working in ARC projects?
On my side I'm using [[[NSUserNotification alloc] init] autorelease] and no problem.

**Comment by aglv** [comment]
I'm still a bit skeptical about this change. Growl has many more notification delivery options (SMS, email, ...) and some users may miss that.

**Comment by derreisende77** [comment]
Growl is basically unmaintained code that currently still works. Latest release I have seen is 4 years old.
Yes I do use ARC in projects but so far I have found one Qt sample that uses Autorelease. All other sample code never released. But as you said it might be due to ARC

**Comment by fvpolpeta** [comment]
Hi @derreisende77 and @aglv 

I don't promise to do this quickly, but I believe both can co-exist behind an abstraction notification.

I understand arguments Growl is old, but I also understand that there are other places in the code that requires attention and the fact that some users may still rely on Growl due to other means.

I will try to see the extension of this work and then make it available in Horos 4.0.0. No timeframe defined yet as we are waiting for some bug resolution in Mojave.

Your feedback and help is much appreciated.

Cheers

Fauze

**Comment by jensen0914** [comment]
Work done to solve notarization issues required removing Growl framework and replacing with UserNotifications framework. See pull request #554 (commit https://github.com/horosproject/horos/pull/554/commits/f9825a38b33f1506601964fa149ef0de6eeb7576)

**Pull request closed without merging**
