### PR TITLE
[FIX] load .horosplugins, but .osirixplugins too

### PR DESCRIPTION
**Pull request by aglv**

### CODE REVIEW

**Comment by spalte** [comment]
I expect that the two projects are going to drift appart, and that it will be unreasonable for Horos to just assume OsiriX plugins to be compatible. I suggest that Horos look for a "HorosCompatible" flag in he osirixPlugin's info.plist to make sure that a given plugin is in fact compatible.

**Comment by aglv** [comment]
I would support the existence of such a flag, but that doesn't exclude .osirixplugins completely. We'll see if @fvpolpeta merges or rejects this. I hope the "osirixplugin" to "horosplugin" switch was intended for the icon.

**Comment by aglv** [comment]
Oh, okay. I looked at the past week's activity around global variables renames and well, yeah, basically horos/osirix plugin compatibility is compromised. Bad, bad bad bad news for us :(

**Comment by fvpolpeta** [comment]
We will be thinking about a strategy for having horos and osirix plugins co-existing. Anyway, if plugins with same purpose - and then possibly with similar class names - are used, we will have problems. A curation strategy will be created in right moment.

Which are the plugins - perhaps of your authoring - that you want to make compatible?

Thanks for your help.

BR

**Comment by aglv** [comment]
All of them, ideally without having to _make_ them compatible. If I have to work more to make a plugin available to both OsiriX and Horos, I'll make my clients choose either one. If they want both, I'll charge more.
API changes should be avoided unless necessary. Global variables plugins may rely on should keep their name, otherwise dynamic linking breaks. 
For example, the one commit that troubled me is 8b5fb8e, I didn't look any further:

> -extern NSString *pasteBoardOsiriX;
>  -extern NSString *pasteBoardOsiriXPlugin;
>  -extern NSString *OsirixPluginPboardUTI;
>  +extern NSString *pasteBoardHoros;
>  +extern NSString *pasteBoardHorosPlugin;
>  +extern NSString *HorosPluginPboardUTI;

I remember of some plugins that rely on those so they can receive drags from the BrowserController. Some older plugins even rely on the string values you reassigned ("OsiriX pasteboard" to "Horos pasteboard"), but others rely on the global variables you renamed (OsirixPluginPboardUTI to HorosPluginPboardUTI).

You should deprecate the OsiriX globals and introduce new ones, and avoid switching the strings. I know, they're pretty dirty, the temptation is strong. Now, if you want, I could go through your commits and revert the things that I know will cause problems, but maybe this forking away from OsiriX is a choice? It is inevitable in the long term, but why push it?

**Comment by fvpolpeta** [comment]
I started to push it because there were some users reporting that some plugins stopped working and also some runtime exceptions in Horos were happening. Based on logs, I did notice that was related to one plugin and another. Conclusion: after a plugin update, changes to these plugins were no longer matching the interfaces (i.e. runtime calls to undefined methods). 

Hence, I do not see ways of making this works without a curation strategy since osirix plugins binaries comes from a server we do not maintain, and are not monitoring for updates. It's less expensive to have a solid working plugin database than users reporting sporadic crashes saying that this kind of thing doesn't happen in OsiriX.

**Comment by aglv** [comment]
So, no longer loading .osirixplugins, only .horosplugins?

**Comment by fvpolpeta** [comment]
After some quick internal brainstorm, we decided to create a way of transferring the responsibility of compatibility curation to developers and users.

We will be creating a plugin loading panel where users will be able to keep activated what they want (all horosplugins, all osirixplugins, individual plugins, etc). From there they will be warned about possible not-validated code, etc.

This will at least generate an attempt to make plugin developers to validate their work in both platforms. And users will be able to load/unload what they want. Course, a second app will be necessary to manipulate the list of loaded plugins, if not a second app, avoid loading of plugins in protected mode. 

We can go further and try to monitor which plugins caused crashes.

So, finally, both will be accepted.

Your opinion please?

BR

**Comment by fvpolpeta** [comment]
(There might be crashes during loading time. Then the need of 2nd app or plugin-protected mode)

**Comment by aglv** [comment]
Giving users the choice sounds reasonable to me. I'd also take Joël's suggestion into account - maybe, if a plugin is marked as HorosCompatible in its Info.plist, make it more likely to be loaded in some in-between plugins loading setting, at least as a by-default, initial setting.

**Comment by fvpolpeta** [comment]
Perfect. Horos compatible flagged plugins are in principle loaded by default.

That was a great discussion. Thanks for sharing your ideas with us.

We talk

BR

**Comment by spalte** [comment]
Let me also throw out some more tags that I think are worth discussing...

A compatible-version key. So that you know what versions that plugin has been validated for. (maybe present a warning to the user)
Developer email and URL keys so that you can point the user to the right person when there is a problem.
A key with a URL to the latest version so that you can give the option to automatically update. For security it might be a good idea if you require the plugin to be signed for this to happen though.

**Comment by aglv** [comment]
The latest commit fixes the matrix selection issues for me. I changed the confusing BrowserMatrix cell state+selection+highlight to a more simplified state+selection system. Highlight is not displayed anymore. I hope this works for you.

**Pull request merged**
